name: Build Docker Image on Feature Branch

on:
  push:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Required for OIDC authentication

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.TEXAS_MANAGEMENT_ACCOUNT_ID}}:role/bs-select-jenkins-assume-role
          aws-region: eu-west-2
          output-credentials: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2         # Optional, specify if using a private registry

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{secrets.ECR_REPOSITORY}}
          BRANCH_NAME: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          IMAGE_TAG: ${BRANCH_NAME#*/} # Remove everything before the first '/'
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG




