name: Build Docker Image on Feature Branch

on:
  push:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ECR_REPOSITORY: ${{secrets.TEXAS_MANAGEMENT_ACCOUNT_ID}}.dkr.ecr.eu-west-2.amazonaws.com
      IMAGE_NAME: bs-select-playwright-test
    permissions:
      contents: read
      id-token: write  # Required for OIDC authentication

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.TEXAS_NONPROD_ACCOUNT_ID}}:role/bs-select-jenkins-assume-role
          aws-region: eu-west-2
          output-credentials: true

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ECR_REPOSITORY }}      # Optional, specify if using a private registry

      - name: Build, tag, and push Docker image
        env:
          BRANCH_NAME: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
        run: |
          IMAGE_TAG="${BRANCH_NAME#*/}"
          echo "Image tag: $IMAGE_TAG"

          docker build -f buildBase.dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          echo "ECR Repository: $ECR_REPOSITORY"

          docker push ${{env.ECR_REPOSITORY}}/${{env.IMAGE_NAME}}:$IMAGE_TAG
