name: Full CI/CD + Docker

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  ci_cd:
    uses: ./.github/workflows/cicd-1-pull-request.yaml
    secrets: inherit

  build_docker:
    name: Build Docker Image
    needs: ci_cd
    if: ${{ success() }}
    uses: ./.github/workflows/build-base.yaml
    secrets: inherit
