name: Push to any branch

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  ci_cd:
    name: CI / CD
    uses: ci-cd.yaml
    secrets: inherit

  build_docker:
    name: Build Docker Image
    needs: ci_cd
    uses: build-docker-image.yaml
    secrets: inherit
