name: Push to any branch

on:
  push:
    branches:
      - "**"

jobs:
  ci_cd:
    name: CI / CD
    uses: ./.github/workflows/ci-cd.yaml
    secrets: inherit

  build_docker:
    name: Build Docker Image
    needs: ci_cd
    uses: ./.github/workflows/build-docker-image.yaml
    secrets: inherit
