name: Remove Docker Image

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main
  #   if: github.event.pull_request.merged == true

jobs:
  remove-image:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: ${{secrets.TEXAS_MANAGEMENT_ACCOUNT_ID}}.dkr.ecr.eu-west-2.amazonaws.com
      IMAGE_NAME: bs-select-playwright-test
    permissions:
      contents: read
      id-token: write  # Re
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.TEXAS_NONPROD_ACCOUNT_ID}}:role/bs-select-jenkins-assume-role
          aws-region: eu-west-2
          output-credentials: true

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ECR_REPOSITORY }}

      - name: Remove Docker Image
        run: |
          # Extract the ticket from the branch name

          BRANCH_NAME="${{ github.ref_name }}"
          TICKET=$(echo "$BRANCH_NAME" | grep -oiE '[a-z]+[0-9]+-[0-9]+')
          IMAGE_TAG="${TICKET}_current"
          IMAGE_TAG="${IMAGE_TAG,,}"  # Convert to lower case

          docker rmi ${{env.ECR_REPOSITORY}}/${{env.IMAGE_NAME}}:$IMAGE_TAG || echo "Image not found"
